// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_9Ea7P8unsUMGnUvDIzFZWZc7IoGQV4Y',
    appId: '1:711225625151:android:a5a0bd6458fdab64aec68a',
    messagingSenderId: '711225625151',
    projectId: 'milo-e67f7',
    databaseURL: 'https://milo-e67f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'milo-e67f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMWJYRwAPtLWF0ZtQhQaSYZXfKvVGeTKk',
    appId: '1:711225625151:ios:6a96dc16e37e62d3aec68a',
    messagingSenderId: '711225625151',
    projectId: 'milo-e67f7',
    databaseURL: 'https://milo-e67f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'milo-e67f7.appspot.com',
    iosClientId: '711225625151-be4rt776i3gdfjlhue5qjj024hm8e99d.apps.googleusercontent.com',
    iosBundleId: 'com.milo.milo',
  );
}
